Algoritmo "Ficha 5 exercicio 3"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 1/29/2022
Var
// Seção de Declarações das variáveis 
val1, val2: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   escreva("Insira um valor: ")
   leia(val1)
   escreva("Insira outro valor: ")
   leia(val2)
   se (val1%val2) = 0 entao
      escreval("O", val1, " é multiplo de ",val2,".")
   senao
      escreval("O", val1, " não é multiplo de ",val2,".")
   fimse
   

Fimalgoritmo